spring.application.name=backend
spring.datasource.url=jdbc:mysql://10.0.2.10:3306/ropitadb
spring.datasource.username=backend
spring.datasource.password=ropa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080